name: joyful_noise
description: A Very Good Project created by Very Good CLI.
version: 1.0.14
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  auto_size_text: ^3.0.0
  collection: ^1.17.0
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter_svg: ^1.1.6
  websafe_svg: ^2.1.3+1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_riverpod: ^2.1.3
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.1.3
  intl: ^0.18.0
  oauth2: ^2.0.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  path: ^1.8.2
  responsive_framework: ^0.2.0
  riverpod: ^2.1.3
  webview_flutter: ^4.0.4
  sembast: ^3.2.0
  path_provider: ^2.0.9
  flash: ^2.0.3+2
  cached_network_image: ^3.2.0
  sembast_web: ^2.0.1+1
  platform: ^3.1.0
  shimmer: ^2.0.0
  flutter_chord:
    git:
      url: https://github.com/paurakhsharma/flutter_chord
  flutter_guitar_tabs: ^0.0.8
  material_floating_search_bar:
    git:
      url: https://github.com/jeremiahlukus/material_floating_search_bar
  just_audio: ^0.9.29
  rxdart: ^0.27.5
  newrelic_mobile: ^0.0.1-dev.9
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_phoenix: ^1.1.0
  import_sorter: ^4.6.0
  auto_route_generator: ^5.0.3
  alchemist: ^0.6.0
  build_runner: ^2.1.8
  derry: ^1.4.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
  test: ^1.19.5
  patrol: ^1.0.0
  webview_flutter_platform_interface: ^2.0.1


scripts: derry.yaml
patrol:
  app_name: Joyful Noise
  android:
    package_name: com.jparrack.joyful_noise.RunnerUITests
  ios:
    bundle_id: com.jparrack.joyful-noise.RunnerUITests

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - .env.staging
    - .env.dev
    - .env.production
    - .env
