name: joyful_noise
description: A Very Good Project created by Very Good CLI.
version: 1.9.28+28

publish_to: none

environment:
  sdk: ">=3.1.0 <3.2.2"

dependencies:
  pitch_detector_dart: ^0.0.2
  pitchupdart:
    git: 
      url: 'https://github.com/jeremiahlukus/pitchup_dart'
  flutter_audio_capture: ^1.1.4
  syncfusion_flutter_gauges: ^21.1.41
  permission_handler: ^10.2.0
  sleek_circular_slider: ^2.0.1
  google_fonts: ^6.1.0
  sentry_flutter: ^7.10.1
  url_launcher: ^6.1.14
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  collection: ^1.17.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.1.3
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.3
  intl: ^0.18.0
  oauth2: ^2.0.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.2
  responsive_framework: ^0.2.0
  riverpod: ^2.4.3
  webview_flutter: ^4.4.1
  sembast: ^3.5.0+1
  path_provider: ^2.1.1
  flash: ^3.0.5+1
  cached_network_image: ^3.3.0
  sembast_web: ^2.0.3
  platform: ^3.1.3
  shimmer: ^3.0.0
  flutter_chord:
    git:
      url: https://github.com/jeremiahlukus/flutter_chord
  flutter_guitar_tabs: ^0.0.10
  material_floating_search_bar_2: ^0.5.0
  just_audio: ^0.9.35
  rxdart: ^0.27.7
  flutter_dotenv: ^5.1.0
  upgrader: ^8.2.0
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0


dev_dependencies:
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1
  import_sorter: ^4.6.0
  auto_route_generator: ^7.3.2
  alchemist: ^0.7.0
  build_runner: ^2.4.6
  derry: ^1.5.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0
  test: ^1.19.5
  webview_flutter_platform_interface: ^2.0.1


scripts: derry.yaml

flutter:
  uses-material-design: true
  assets:
    - .env.staging
    - .env.dev
    - .env.production
    - .env
